server:
  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: "*"
schema: openapi
#schema: swagger
allowed-origins: http://localhost:3034,http://localhost:9090,http://192.168.100.36:3034