version: "3"
services:
  gateway:
    image: graphql_gateway:latest
    container_name: graphql-gateway
    ports:
      - "8000:8000"
    build: 
      context: graphql-gateway-server/
      dockerfile: Dockerfile
    networks:
      - listing-network
networks:
  listing-network:
    external: true